#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define POWER_CHARGE_DETECT_PIN GPIO_NUM_21
#define POWER_ADC_UNIT ADC_UNIT_2
#define POWER_ADC_CHANNEL ADC_CHANNEL_3

#define RIGHT_LEG_PIN GPIO_NUM_14
#define RIGHT_FOOT_PIN GPIO_NUM_3
#define LEFT_LEG_PIN GPIO_NUM_48
#define LEFT_FOOT_PIN GPIO_NUM_45

#define LEFT_HAND_PIN GPIO_NUM_NC
#define RIGHT_HAND_PIN GPIO_NUM_NC

#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_42
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_41
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_38
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_39
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_40

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_46
#define DISPLAY_MOSI_PIN GPIO_NUM_47
#define DISPLAY_CLK_PIN GPIO_NUM_21
#define DISPLAY_DC_PIN GPIO_NUM_43
#define DISPLAY_RST_PIN GPIO_NUM_NC
#define DISPLAY_CS_PIN GPIO_NUM_44

#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true
#define DISPLAY_RGB_ORDER LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 3

#define BOOT_BUTTON_GPIO GPIO_NUM_0

/* Camera PINs*/
#define OTTO_CAMERA_XCLK      (GPIO_NUM_15)
#define OTTO_CAMERA_PCLK      (GPIO_NUM_13)
#define OTTO_CAMERA_VSYNC     (GPIO_NUM_6)
#define OTTO_CAMERA_HSYNC     (GPIO_NUM_7)
#define OTTO_CAMERA_D0        (GPIO_NUM_11)
#define OTTO_CAMERA_D1        (GPIO_NUM_9)
#define OTTO_CAMERA_D2        (GPIO_NUM_8)
#define OTTO_CAMERA_D3        (GPIO_NUM_10)
#define OTTO_CAMERA_D4        (GPIO_NUM_12)
#define OTTO_CAMERA_D5        (GPIO_NUM_18)
#define OTTO_CAMERA_D6        (GPIO_NUM_17)
#define OTTO_CAMERA_D7        (GPIO_NUM_16)

#define OTTO_CAMERA_PWDN      (GPIO_NUM_NC)
#define OTTO_CAMERA_RESET     (GPIO_NUM_NC)
#define OTTO_CAMERA_XCLK      (GPIO_NUM_15)
#define OTTO_CAMERA_PCLK      (GPIO_NUM_13)
#define OTTO_CAMERA_VSYNC     (GPIO_NUM_6)
#define OTTO_CAMERA_HSYNC     (GPIO_NUM_7)

#define OTTO_CAMERA_XCLK_FREQ (16000000)
#define OTTO_LEDC_TIMER       (LEDC_TIMER_0)
#define OTTO_LEDC_CHANNEL     (LEDC_CHANNEL_0)

#define OTTO_CAMERA_SIOD      (GPIO_NUM_4)
#define OTTO_CAMERA_SIOC      (GPIO_NUM_5)

#define OTTO_ROBOT_VERSION "1.4.4"

#endif  // _BOARD_CONFIG_H_
